/** @type {import('tailwindcss').Config} */
export default {
  content: ["./backend/routes/**/*.ejs"],
  theme: {
    extend: {},
  },
  plugins: [require("@tailwindcss/forms")],
  safelist: [
    "W",
    "Y",
    "R",
    "B",
    "G",
    "downCard",
    "black13",
    "yellow13",
    "red13",
    "blue13",
    "green13",
    "black14",
    "yellow14",
    "red14",
    "blue14",
    "green14",
    "red0",
    "red1",
    "red2",
    "red3",
    "red4",
    "red5",
    "red6",
    "red7",
    "red8",
    "red9",
    "redDraw2",
    "redSkip",
    "redRev",
    "yellow0",
    "yellow1",
    "yellow2",
    "yellow3",
    "yellow4",
    "yellow5",
    "yellow6",
    "yellow7",
    "yellow8",
    "yellow9",
    "yellowDraw2",
    "yellowSkip",
    "yellowRev",
    "blue0",
    "blue1",
    "blue2",
    "blue3",
    "blue4",
    "blue5",
    "blue6",
    "blue7",
    "blue8",
    "blue9",
    "blueDraw2",
    "blueSkip",
    "blueRev",
    "green0",
    "green1",
    "green2",
    "green3",
    "green4",
    "green5",
    "green6",
    "green7",
    "green8",
    "green9",
    "greenDraw2",
    "greenSkip",
    "greenRev",
  ],
};
